# Generated by Django 4.2.7 on 2025-10-01 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_fixedfieldsbyadmin_companyfields_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyfields",
            name="fixed_field",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="CompanyFields",
        ),
        migrations.DeleteModel(
            name="FixedFieldsByAdmin",
        ),
    ]
