# Generated by Django 4.2.7 on 2026-03-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_usersubscription_user_userpaymentmethod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpaymentmethod",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="userpaymentmethod",
            name="cvc",
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userpaymentmethod",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userpaymentmethod",
            name="last4",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="userpaymentmethod",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
