# Generated by Django 4.2.7 on 2026-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_userpaymentmethod_card_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpaymentmethod",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
