# Generated by Django 4.2.7 on 2026-03-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_userpaymentmethod_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
