#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

gunicorn store_core.wsgi --workers 3 --timeout 600 --bind 0.0.0.0:8000