#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

python /app/manage.py migrate

gunicorn docugen.wsgi --workers 3 --timeout 600 --bind 0.0.0.0:8000